// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ0LG5SgYElH8YX3eceshWgmjKTXiVLi4',
    appId: '1:144936244134:web:5aaea15b9574e2e2b13567',
    messagingSenderId: '144936244134',
    projectId: 'hxhp1-580ec',
    authDomain: 'hxhp1-580ec.firebaseapp.com',
    storageBucket: 'hxhp1-580ec.firebasestorage.app',
    measurementId: 'G-WE22WNDVH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzFDAgq83Vh-3mPB6-aGZrghqIb0b0zQk',
    appId: '1:144936244134:android:86e3087801dd0836b13567',
    messagingSenderId: '144936244134',
    projectId: 'hxhp1-580ec',
    storageBucket: 'hxhp1-580ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO8tAi2ukH0WuQR2YGyIrC7y7-OB8eT9I',
    appId: '1:144936244134:ios:6a13a5ede9521e8ab13567',
    messagingSenderId: '144936244134',
    projectId: 'hxhp1-580ec',
    storageBucket: 'hxhp1-580ec.firebasestorage.app',
    iosBundleId: 'com.example.sih',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO8tAi2ukH0WuQR2YGyIrC7y7-OB8eT9I',
    appId: '1:144936244134:ios:6a13a5ede9521e8ab13567',
    messagingSenderId: '144936244134',
    projectId: 'hxhp1-580ec',
    storageBucket: 'hxhp1-580ec.firebasestorage.app',
    iosBundleId: 'com.example.sih',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ0LG5SgYElH8YX3eceshWgmjKTXiVLi4',
    appId: '1:144936244134:web:bcee712d21e87854b13567',
    messagingSenderId: '144936244134',
    projectId: 'hxhp1-580ec',
    authDomain: 'hxhp1-580ec.firebaseapp.com',
    storageBucket: 'hxhp1-580ec.firebasestorage.app',
    measurementId: 'G-GJH39HLH9C',
  );
}
